/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Week8 */

#ifndef _Included_Week8
#define _Included_Week8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Week8
 * Method:    calculateStdDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Week8_calculateStdDev
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Week8
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Week8_calculateMean
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
